name: Test Deployemnt

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  jobOne:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Reposetory
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          echo: "Running Installing Dependencies"
          npm install
      
            
